### ISSUE TITLE
[14.0] attachment_s3: Attachment migration not happening

### ISSUE THREAD

**Issue by gustavovalverde** [camptocamp/odoo-cloud-platform#217]
After configuring `ir_attachment.location` to `s3`, setting the environment variables and installing the attachment_s3 module, I created a server action with `env['ir.attachment'].force_storage()` which shows _"migrating files to the object storage"_ but nothings happens. 

I can also confirm that uploading new PDFs does not use the S3. How can I confirm if I'm missing something?

**Comment by yvaucher** [comment]
@gustavovalverde is the module loaded with `--load` ?

Is `ir_attachment.location` set to `s3` ?


Otherwise, did you set anything in `ir_attachment.storage.force.database` ir.config.parameter?

By default it will always store few things into the database: `{"image/": 51200, "application/javascript": 0, "text/css": 0}`

In your case it could be that `pdf` was added to the list.
