### ISSUE TITLE
_inverse_datas not callled

### ISSUE THREAD

**Issue by tschanzt** [camptocamp/odoo-cloud-platform#63]
base_attachment_object_storage in v9 defines a function called _inverse_datas. The default inverse function for datas (https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_attachment.py#L279) is _data_set so it will not be called. 

We define a datas field in attachment_s3 which uses _inverse_datas a inverse.  Can we move it? currently there is no dependency between the two afterwards attachment_s3 would have to depend on base_attachment_object_storage

**Comment by guewen** [comment]
We should apply the same fix as the one done in [attachment_s3](https://github.com/camptocamp/odoo-cloud-platform/blob/92ca087101fa0c273fb184a1eca10fa3e3e2c814/attachment_s3/models/ir_attachment.py#L53-L61) but in base_attachment_object_storage.

In 9.0, attachment_s3 does not depend on  base_attachment_object_storage because it was written before and the latter is a backport. We have to duplicate this part.
